.TH "TTN-LW-CLI" "1" "Feb 2019" "TTN" "The Things Network Stack for LoRaWAN" 
.nh
.ad l


.SH NAME
.PP
ttn\-lw\-cli\-gateways\-rights \- List the rights to a gateway


.SH SYNOPSIS
.PP
\fBttn\-lw\-cli gateways rights [flags]\fP


.SH DESCRIPTION
.PP
List the rights to a gateway


.SH OPTIONS
.PP
\fB\-\-gateway\-eui\fP=""

.PP
\fB\-\-gateway\-id\fP=""

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rights


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-application\-server\-address\fP="localhost:8884"
    Application Server Address

.PP
\fB\-\-ca\fP=""
    CA certificate file

.PP
\fB\-c\fP, \fB\-\-config\fP=[$HOME/.ttn\-lw\-cli.yml]
    Location of the config files

.PP
\fB\-\-gateway\-server\-address\fP="localhost:8884"
    Gateway Server Address

.PP
\fB\-\-identity\-server\-address\fP="localhost:8884"
    Identity Server Address

.PP
\fB\-\-input\-format\fP="json"
    Input format

.PP
\fB\-\-insecure\fP[=false]
    Connect without TLS

.PP
\fB\-\-join\-server\-address\fP="localhost:8884"
    Join Server Address

.PP
\fB\-\-log.level\fP="info"
    The minimum level log messages must have to be shown

.PP
\fB\-\-network\-server\-address\fP="localhost:8884"
    Network Server Address

.PP
\fB\-\-oauth\-server\-address\fP="
\[la]https://localhost:8885"\[ra]
    OAuth Server Address

.PP
\fB\-\-output\-format\fP="json"
    Output format


.SH SEE ALSO
.PP
\fBttn\-lw\-cli\-gateways(1)\fP
