.TH "TTN-LW-CLI" "1" "Feb 2019" "TTN" "The Things Network Stack for LoRaWAN" 
.nh
.ad l


.SH NAME
.PP
ttn\-lw\-cli\-applications\-webhook\-get \- Get the properties of an application webhook


.SH SYNOPSIS
.PP
\fBttn\-lw\-cli applications webhook get [flags]\fP


.SH DESCRIPTION
.PP
Get the properties of an application webhook


.SH OPTIONS
.PP
\fB\-\-application\-id\fP=""

.PP
\fB\-\-base\-url\fP[=false]
    select the base\_url field

.PP
\fB\-\-downlink\-ack\fP[=false]
    select the downlink\_ack field and all sub\-fields

.PP
\fB\-\-downlink\-ack.path\fP[=false]
    select the downlink\_ack.path field

.PP
\fB\-\-downlink\-failed\fP[=false]
    select the downlink\_failed field and all sub\-fields

.PP
\fB\-\-downlink\-failed.path\fP[=false]
    select the downlink\_failed.path field

.PP
\fB\-\-downlink\-nack\fP[=false]
    select the downlink\_nack field and all sub\-fields

.PP
\fB\-\-downlink\-nack.path\fP[=false]
    select the downlink\_nack.path field

.PP
\fB\-\-downlink\-queued\fP[=false]
    select the downlink\_queued field and all sub\-fields

.PP
\fB\-\-downlink\-queued.path\fP[=false]
    select the downlink\_queued.path field

.PP
\fB\-\-downlink\-sent\fP[=false]
    select the downlink\_sent field and all sub\-fields

.PP
\fB\-\-downlink\-sent.path\fP[=false]
    select the downlink\_sent.path field

.PP
\fB\-\-format\fP[=false]
    select the format field

.PP
\fB\-\-headers\fP[=false]
    select the headers field

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for get

.PP
\fB\-\-join\-accept\fP[=false]
    select the join\_accept field and all sub\-fields

.PP
\fB\-\-join\-accept.path\fP[=false]
    select the join\_accept.path field

.PP
\fB\-\-location\-solved\fP[=false]
    select the location\_solved field and all sub\-fields

.PP
\fB\-\-location\-solved.path\fP[=false]
    select the location\_solved.path field

.PP
\fB\-\-uplink\-message\fP[=false]
    select the uplink\_message field and all sub\-fields

.PP
\fB\-\-uplink\-message.path\fP[=false]
    select the uplink\_message.path field

.PP
\fB\-\-webhook\-id\fP=""


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-application\-server\-address\fP="localhost:8884"
    Application Server Address

.PP
\fB\-\-ca\fP=""
    CA certificate file

.PP
\fB\-c\fP, \fB\-\-config\fP=[$HOME/.ttn\-lw\-cli.yml]
    Location of the config files

.PP
\fB\-\-gateway\-server\-address\fP="localhost:8884"
    Gateway Server Address

.PP
\fB\-\-identity\-server\-address\fP="localhost:8884"
    Identity Server Address

.PP
\fB\-\-input\-format\fP="json"
    Input format

.PP
\fB\-\-insecure\fP[=false]
    Connect without TLS

.PP
\fB\-\-join\-server\-address\fP="localhost:8884"
    Join Server Address

.PP
\fB\-\-log.level\fP="info"
    The minimum level log messages must have to be shown

.PP
\fB\-\-network\-server\-address\fP="localhost:8884"
    Network Server Address

.PP
\fB\-\-oauth\-server\-address\fP="
\[la]https://localhost:8885"\[ra]
    OAuth Server Address

.PP
\fB\-\-output\-format\fP="json"
    Output format


.SH SEE ALSO
.PP
\fBttn\-lw\-cli\-applications\-webhook(1)\fP
