.TH "TTN-LW-CLI" "1" "Feb 2019" "TTN" "The Things Network Stack for LoRaWAN" 
.nh
.ad l


.SH NAME
.PP
ttn\-lw\-cli\-applications\-api\-keys\-update \- Update an application API key


.SH SYNOPSIS
.PP
\fBttn\-lw\-cli applications api\-keys update [flags]\fP


.SH DESCRIPTION
.PP
Update an application API key


.SH OPTIONS
.PP
\fB\-\-api\-key\-id\fP=""

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for update

.PP
\fB\-\-name\fP=""

.PP
\fB\-\-right\-application\-all\fP[=false]

.PP
\fB\-\-right\-application\-delete\fP[=false]

.PP
\fB\-\-right\-application\-devices\-read\fP[=false]

.PP
\fB\-\-right\-application\-devices\-read\-keys\fP[=false]

.PP
\fB\-\-right\-application\-devices\-write\fP[=false]

.PP
\fB\-\-right\-application\-devices\-write\-keys\fP[=false]

.PP
\fB\-\-right\-application\-info\fP[=false]

.PP
\fB\-\-right\-application\-link\fP[=false]

.PP
\fB\-\-right\-application\-settings\-api\-keys\fP[=false]

.PP
\fB\-\-right\-application\-settings\-basic\fP[=false]

.PP
\fB\-\-right\-application\-settings\-collaborators\fP[=false]

.PP
\fB\-\-right\-application\-traffic\-down\-write\fP[=false]

.PP
\fB\-\-right\-application\-traffic\-read\fP[=false]

.PP
\fB\-\-right\-application\-traffic\-up\-write\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-application\-id\fP=""

.PP
\fB\-\-application\-server\-address\fP="localhost:8884"
    Application Server Address

.PP
\fB\-\-ca\fP=""
    CA certificate file

.PP
\fB\-c\fP, \fB\-\-config\fP=[$HOME/.ttn\-lw\-cli.yml]
    Location of the config files

.PP
\fB\-\-gateway\-server\-address\fP="localhost:8884"
    Gateway Server Address

.PP
\fB\-\-identity\-server\-address\fP="localhost:8884"
    Identity Server Address

.PP
\fB\-\-input\-format\fP="json"
    Input format

.PP
\fB\-\-insecure\fP[=false]
    Connect without TLS

.PP
\fB\-\-join\-server\-address\fP="localhost:8884"
    Join Server Address

.PP
\fB\-\-log.level\fP="info"
    The minimum level log messages must have to be shown

.PP
\fB\-\-network\-server\-address\fP="localhost:8884"
    Network Server Address

.PP
\fB\-\-oauth\-server\-address\fP="
\[la]https://localhost:8885"\[ra]
    OAuth Server Address

.PP
\fB\-\-output\-format\fP="json"
    Output format


.SH SEE ALSO
.PP
\fBttn\-lw\-cli\-applications\-api\-keys(1)\fP
