.TH "TTN-LW-CLI" "1" "Feb 2019" "TTN" "The Things Network Stack for LoRaWAN" 
.nh
.ad l


.SH NAME
.PP
ttn\-lw\-cli\-gateways\-list \- List gateways


.SH SYNOPSIS
.PP
\fBttn\-lw\-cli gateways list [flags]\fP


.SH DESCRIPTION
.PP
List gateways


.SH OPTIONS
.PP
\fB\-\-antennas\fP[=false]
    select the antennas field

.PP
\fB\-\-attributes\fP[=false]
    select the attributes field

.PP
\fB\-\-auto\-update\fP[=false]
    select the auto\_update field

.PP
\fB\-\-contact\-info\fP[=false]
    select the contact\_info field

.PP
\fB\-\-description\fP[=false]
    select the description field

.PP
\fB\-\-downlink\-path\-constraint\fP[=false]
    select the downlink\_path\_constraint field

.PP
\fB\-\-enforce\-duty\-cycle\fP[=false]
    select the enforce\_duty\_cycle field

.PP
\fB\-\-frequency\-plan\-id\fP[=false]
    select the frequency\_plan\_id field

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for list

.PP
\fB\-\-location\-public\fP[=false]
    select the location\_public field

.PP
\fB\-\-name\fP[=false]
    select the name field

.PP
\fB\-\-organization\-id\fP=""

.PP
\fB\-\-schedule\-downlink\-late\fP[=false]
    select the schedule\_downlink\_late field

.PP
\fB\-\-status\-public\fP[=false]
    select the status\_public field

.PP
\fB\-\-update\-channel\fP[=false]
    select the update\_channel field

.PP
\fB\-\-user\-id\fP=""

.PP
\fB\-\-version\-ids\fP[=false]
    select the version\_ids field and all sub\-fields

.PP
\fB\-\-version\-ids.brand\-id\fP[=false]
    select the version\_ids.brand\_id field

.PP
\fB\-\-version\-ids.firmware\-version\fP[=false]
    select the version\_ids.firmware\_version field

.PP
\fB\-\-version\-ids.hardware\-version\fP[=false]
    select the version\_ids.hardware\_version field

.PP
\fB\-\-version\-ids.model\-id\fP[=false]
    select the version\_ids.model\_id field


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-application\-server\-address\fP="localhost:8884"
    Application Server Address

.PP
\fB\-\-ca\fP=""
    CA certificate file

.PP
\fB\-c\fP, \fB\-\-config\fP=[$HOME/.ttn\-lw\-cli.yml]
    Location of the config files

.PP
\fB\-\-gateway\-server\-address\fP="localhost:8884"
    Gateway Server Address

.PP
\fB\-\-identity\-server\-address\fP="localhost:8884"
    Identity Server Address

.PP
\fB\-\-input\-format\fP="json"
    Input format

.PP
\fB\-\-insecure\fP[=false]
    Connect without TLS

.PP
\fB\-\-join\-server\-address\fP="localhost:8884"
    Join Server Address

.PP
\fB\-\-log.level\fP="info"
    The minimum level log messages must have to be shown

.PP
\fB\-\-network\-server\-address\fP="localhost:8884"
    Network Server Address

.PP
\fB\-\-oauth\-server\-address\fP="
\[la]https://localhost:8885"\[ra]
    OAuth Server Address

.PP
\fB\-\-output\-format\fP="json"
    Output format


.SH SEE ALSO
.PP
\fBttn\-lw\-cli\-gateways(1)\fP
